### ISSUE TITLE
"Managing Organizations and Locations" chapter missing

### ISSUE THREAD

**Issue by maximiliankolb** [theforeman/foreman-documentation#1165]
Hey.
I cannot find the chapter "Managing Organizations and Locations" anymore.

With 2.5: it's part of the [content management guide](https://docs.theforeman.org/2.5/Content_Management_Guide/index-katello.html#Managing_Organizations).
with nightly: [I cannot find it](https://docs.theforeman.org/release/nightly/)

If I truely understood how we build the web stuff, I would open a PR. 🙈

**Comment by maximiliankolb** [comment]
Yes, that's what I was looking for. I might need new glasses, but still cannot find it in the menu structure. Can you?

**Comment by ekohl** [comment]
No, it isn't there. This is probably an oversight. However, I think all the landing pages need a very thorough look. For example, the top navigation is (correctly) all split into various builds but the landing pages are plain lists. This is inconsistent but I'm not sure how to otherwise present it.

Perhaps we need to just link to the most critical ones (quick start, install guide, release notes, planning guide, not necessarily in that order) for each flavor, presenting them side by side. Then also a quick note what the status is (RC/supported/EOL) and that the top navigation has all the links.

**Comment by maximiliankolb** [comment]
I am trying to add this: see https://github.com/theforeman/foreman-documentation/pull/1169

**Comment by ekohl** [comment]
So it also made me read through the document and I came up with https://github.com/theforeman/foreman-documentation/pull/1170

**Comment by maximiliankolb** [comment]
> For future reference, you used `Closes` in #1169 so you don't need to close this. When that PR is merged, this issue will be closed automatically. If that's rejected, we keep the issue open.

Thanks, will do!
