### ISSUE TITLE
3.3 build broken due to link check

### ISSUE THREAD

**Issue by Lennonka** [theforeman/foreman-documentation#1272]
Hi,
A cherry-pick that I did to 3.3 is breaking the build.
The linkchecker-tryer fails on the URL: https://yum.theforeman.org/client/3.3/

I don't know what that is or how to fix it.

Blame commit: https://github.com/theforeman/foreman-documentation/commit/8494e6b6af9e9f23022fb1349bc37cfb4ddb6065

**Comment by Lennonka** [comment]
@maximiliankolb Would you mind taking a look at it, please?

**Comment by maximiliankolb** [comment]
This is an expected failure because the clients for Foreman 3.3 have not been released yet. However, branching for 3.3 was necessary to provide documentation for the RC phase. I would just wait until Foreman 3.3 is released and this directory will exist.

To fix this with a linkchecker exception:

```diff
diff --git a/guides/common/linkchecker.ini b/guides/common/linkchecker.ini
index 58e0ff6c..283be8ee 100644
--- a/guides/common/linkchecker.ini
+++ b/guides/common/linkchecker.ini
@@ -21,3 +21,4 @@ ignore=example.com
   # This isn't published downstream yet
   access.redhat.com/documentation/en-us/red_hat_satellite/6.10/html-single/managing_configurations_using_puppet_integration/index
   access.redhat.com/documentation/en-us/red_hat_satellite/6.11
+  yum.theforeman.org/client/3.3/
```

However, looking at the URL, it's already here, meaning the Pipeline should not fail any more. > I have restarted the GHA.

**Comment by maximiliankolb** [comment]
It's working again without any change necessary: https://github.com/theforeman/foreman-documentation/actions/runs/2315608189
