### ISSUE TITLE
Valid URLs failing html checks

### ISSUE THREAD

**Issue by adamlazik1** [theforeman/foreman-documentation#1831]
I have noticed in the past couple of days that valid URLs fail the html checks. Not any specific URLs also, but each time they seem to be random. 
As an example, in the last check in #1830 it was these URLs:
http://mirror.stream.centos.org/9-stream/BaseOS/x86_64/
https://www.postgresql.org/docs/current/runtime-config-logging.html
Both of them are valid.

Do we have any idea what is causing this issue?

**Comment by ekohl** [comment]
This is a side effect of https://github.com/theforeman/foreman-documentation/commit/babc9d068e0121fd9f42df2574adf8476c0ac6b8. Sadly the linkchecker-tryer package is not compatible with Python 3 and unmaintained since at least 7 years. https://github.com/linkchecker/linkchecker/issues/263 is open to implement it in linckecker itself.

Looking at how simple linkchecker-tryer is we could actually easily implement it again manually using a single file.
