### ISSUE TITLE
Split synchronizing content by sync type

### ISSUE THREAD

**Issue by adamlazik1** [theforeman/foreman-documentation#2118]
Copying comment from https://github.com/theforeman/foreman-documentation/pull/2004#issuecomment-1481238707:

It seems like this entire section is in the wrong place.

There are three types of ISS:

"Export sync" (a.k.a air-gapped / fully disconnected) - use hammer content-export and hammer content-import and move files manually via sneakernet
"Network sync" - use the connected Satellite as the Red Hat CDN URL for the "disconnected" Satellite (which still has a network connection to the connected Satellite, but may not have a connection to the Internet)
Syncable exports & imports - use hammer content-export --format syncable
All of the sections in this chapter, "Synchronizing content between Satellites", are about Export sync. This is the only one that's about Network Sync, and it's in the middle of all the other stuff about Export sync.

Ideally, I think each of the three strategies should have its own documentation section, along with an overview that helps the user decide which one to use. Thoughts?

**Comment by maximiliankolb** [comment]
What's the third type of ISS?

* Export sync: :heavy_check_mark: 
* Network sync: :heavy_check_mark: 
* ???
* misusing (?) ISS for backups: is that somehow possible?

In general, I'd be open to moving the thing to a standalone guide with a bit more context on when to use which procedure. It's currently part of the [Managing Content](https://docs.theforeman.org/nightly/Managing_Content/index-katello.html#Synchronizing_Content_Between_Servers_content-management) guide. Note that build target "satellite" renders things a bit differently.

If we "just" split it into three assemblies, I'd also consider this a true improvement!

cc @bangelic

**Comment by maximiliankolb** [comment]
What the intented use case for this? Does it overlap with the other two use cases above? Is it for backups?

**Comment by adamlazik1** [comment]
I believe @jeremylenz could provide more insight.

**Comment by jeremylenz** [comment]
It's always been three "types of ISS" in my mind because it's three different ways of getting content from one Satellite to another. But as far as what the physical connections look like, there are only two.

| ISS Use case| Physical configuration | What you select in Manifest modal | How you transfer data between Satellites |
| --- | ---| --- | --- |
| Pulpcore import/export| Fully disconnected (Air-gapped) | Export Sync | `hammer content-export` |
| Syncable exports/imports | Fully disconnected (Air-gapped) | Export Sync |  `hammer content-export --format syncable` |
| Network Sync | "Disconnected" | Network Sync | The "disconnected" Satellite consumes content from the connected Satellite |

| Physical configuration | Description |
| --- | --- |
| Fully disconnected (Air-gapped) | The disconnected Satellite is physically disconnected from the internet and all other networks. |
| "Disconnected" | The "disconnected" Satellite cannot communicate with the Internet, but can communicate over the network with the connected Satellite. |

To answer your questions @maximiliankolb, none of these use cases have backups in mind. They are all for operating Satellites that are disconnected from the Internet. For the fully disconnected (air-gapped) configuration, Syncable import/export has some advantages over pulpcore import/exports, mainly that you don't have to have matching Satellite versions.

cc @parthaa who may have more commentary.

**Comment by parthaa** [comment]
As @jeremylenz said.  I'd categorize both regular Import/Export & Syncable Import/Export as Export Sync (as jeremy's table indicates).

**Comment by maximiliankolb** [comment]
docs triage: @adamlazik1 We currently have https://docs.theforeman.org/nightly/Managing_Content/index-katello.html#Synchronizing_Content_Between_Servers_content-management split by sync type and an appendix on how to configure it: https://docs.theforeman.org/nightly/Managing_Content/index-katello.html#Configuring-ISS_content-management

Closing this issue for now unless there's an urgent issue/major benefit to restructure it again.
