### ISSUE TITLE
Differentiate contexts between Installing Server and Installing Server Disconnected

### ISSUE THREAD

**Issue by adamlazik1** [theforeman/foreman-documentation#2159]
I just found out [Installing Server](https://github.com/theforeman/foreman-documentation/blob/master/guides/doc-Installing_Server/master.adoc) and [Installing Server Disconnected](https://github.com/theforeman/foreman-documentation/blob/master/guides/doc-Installing_Server_Disconnected/master.adoc) have the same context for satellite. this causes trouble when trying to differentiate between guides in ifeval directives like in #2157.

It would we best if we changed context of one of these guides. I suspect this can be a lot of work since we would also need to change all links pointing to that guide. At at same time, we cannot just change all the links having the current context of the said guide (and I presume it is more logical to change context of Installing Server Disconnected, since from my understanding, it is only used in Satellite - correct me here if I am wrong) as the context is the same for both guides. So we would need to check the links carefully.

**Comment by maximiliankolb** [comment]
My feeling is that "one guide = one hardcoded context" works well. IMHO `:context: satellite` in "master.adoc" for Server_Disconnected is wrong. Even though it gets rendered only for one build target, it's probably best to give it a unique context like  `{project-context}-disconnected`.

Changing links is always painful, but adding workaround on workaround is no fun in the long run.

Because we don't use the guide in downstream, I have no strong opinion; please consider this a recommendation.

**Comment by adamlazik1** [comment]
I completely agree with you here @maximiliankolb.

**Comment by Lennonka** [comment]
+1 for the suggestion by @maximiliankolb , sounds good.

**Comment by maximiliankolb** [comment]
docs triage: There are currently no open issues related to attributes in "Installing Foreman Server" and "Installing Foreman Server offline". If it comes up again, we have already discusses a possible solution that we can test.

currently available macros: mode = connected/disconnected.
