### ISSUE TITLE
FYI: linkcheck and therefore publishing fails due to Link to "Red Hat Ansible Automation Platform"

### ISSUE THREAD

**Issue by maximiliankolb** [theforeman/foreman-documentation#2185]
cc @Lennonka @adamlazik1

**Comment by adamlazik1** [comment]
I saw this one. I wonder if the ansible link is not going to be available anymore or if it is a temporary outage. That being said, if there is a new version of the docs with which we can replace the link, then we should do that. Unfortunately I do not think I will find the time to do this in this or next week due to different priorities.

**Comment by Lennonka** [comment]
Yep, noticed! Thanks, Max.
Resolved in #2197 and #2198

**Comment by maximiliankolb** [comment]
Thanks Malhar and Lena.
