### ISSUE TITLE
Decide on a name or attribute for hosts

### ISSUE THREAD

**Issue by asteflova** [theforeman/foreman-documentation#2654]
Options suggested by @maximiliankolb:

- Clients?
- Managed hosts?
- Servers? 👎
- Hosts? 👎
- Systems? 👎

**Comment by maximiliankolb** [comment]
Traditionally, in orcharhino, we call them "managed hosts" (hosts that a user deploys/manages/configures) and "orcharhino Clients" as in "we provide repositories for all supported OS" as part of our product.

I am OK with "Clients", esp. compared to "Foreman Server" and "Smart Proxy Server", so we always know which entity we talk about.

**Comment by ekohl** [comment]
> Clients?

This is confusing, because they can be considered a server to other clients.

> Managed hosts?

Managed hosts have a special meaning in Foreman. In the database there's a flag on every host for managed/unmanaged. This is shown in the Edit host page as a `Manage host` or `Unmanage host`. Managed hosts can be provisioned. Unmanaged hosts can still have content.

Reusing the name for a different concept is a recipe for confusion.

> Servers? 👎

This is inventing a new concept and similar to Clients, can be confusing.

> Hosts? 👎

This is what the UI uses all over the place and would be my vote. Otherwise documentation goes out of sync with the product.

> Systems? 👎

A long time ago Katello called Hosts Systems (back when Katello was a standalone application). It was decided to align everything on Hosts.

**Comment by maximiliankolb** [comment]
FYI: Content Hosts is going to disappear soon-ish. probably Foreman 3.10.

Let's go with "Hosts" similar to Foreman Web UI.
