### ISSUE TITLE
Definition for "Enterprise Linux"

### ISSUE THREAD

**Issue by Lennonka** [theforeman/foreman-documentation#2679]
We want to include the definition of this term into the glossary, however, I'm not certain about what the term actually includes.

Does it stand for:

- just RHEL and CentOS
- more RHEL derivatives - which ones?
- any RHEL-derivative OS

We should be careful how we define this. Is it even the same for Foreman and clients?

From the Foreman perspective, we want to say that Foreman can be installed on EL, however, in the [Quickstart guide we explicitly mention only RHEL and CentOS](https://docs.theforeman.org/nightly/Quickstart/index-foreman-el.html).

From the perspective of clients, I guess there's more. Based on what I see in the Installation Media:

- AlmaLinux
- CentOS Linux (including Stream)
- Fedora
- Oracle Linux
- RHEL
- Rocky Linux

So, can be Foreman installed on all those listed OSs?

cc @maximiliankolb @ekohl

**Comment by maximiliankolb** [comment]
In the past, "EL" stood for CentOS Linux 7, RHEL, and Oracle Linux. Now, it stands for AlmaLinux, Oracle Linux, RHEL, and Rocky Linux. I would define EL as "Red Hat Enterprise Linux and its derivatives".

Fedora and CentOS are upstream to RHEL (and therefore EL), but not considered EL.

The other question is: What's the official target OS for Foreman Server/Smart Proxy Server?
* Satellite: RHEL 8
* orcharhino: AlmaLinux 8, Oracle Linux 8, Red Hat Enterprise Linux 8, and Rocky Linux 8
* Foreman/Katello: unsure what it's currently tested against. Maybe EL8 plus CentOS 8 Stream? Do you have a link Ewoud where it's defined in code?

Regarding attributes: It makes sense for us to differenitate between "EL" and "RHEL" because some procedures such as Virt-Who only affect RHEL but not EL. Also content from RH CDN etc.

**Comment by Lennonka** [comment]
Thank you for you contribution.
I'm concluding that the following OS are EL:

- AlmaLinux
- CentOS Linux -- I'd keep this for now, because of Convert2RHEL
- CentOS Stream
- Oracle Linux
- RHEL
- Rocky Linux
