### ISSUE TITLE
Check and (if necessary) update supported versions for upstream and downstreams

### ISSUE THREAD

**Issue by asteflova** [theforeman/foreman-documentation#2775]
assembly_supported-usage-and-versions-of-project-components.adoc includes modules for different upstreams and downstreams. Some of those modules might need to be updated.

**Comment by maximiliankolb** [comment]
file: https://github.com/theforeman/foreman-documentation/blob/master/guides/common/assembly_supported-usage-and-versions-of-project-components.adoc?plain=1

current state:
* Satellite hides supported Foreman OS and Client OS because duh
* orcharhino: does not use "Planning Guide" in downstream docs yet.
* upstream Foreman+Katello: https://docs.theforeman.org/nightly/Planning_for_Project/index-katello.html#Content_Types_in_Foreman_planning :heavy_check_mark: & https://docs.theforeman.org/nightly/Planning_for_Project/index-katello.html#Client-Operating-Systems_planning :heavy_check_mark: 

minor extension for upstream: https://github.com/theforeman/foreman-documentation/pull/3381

-> I propose to close this issue with PR 3381.
