### ISSUE TITLE
attribute.adoc file not updated?

### ISSUE THREAD

**Issue by melcorr** [theforeman/foreman-documentation#297]
Hi @spetrosi @suyogsainkar 

Can you explain to me why the attribute.adoc file is not updated for the 6.8 release? 

Also I see that in #293 links are being manually updated rather than using ProductVersion variable. This seems suboptimal and regressive and will lead to problems a few weeks down the road. 

What's the thinking here?

**Comment by spetrosi** [comment]
> Can you explain to me why the attribute.adoc file is not updated for the 6.8 release?
The version numbers for 6.8 have been updated in the SATELLITE-6.8 branch. This has been done so because checks in this repository check links against the master branch, so if we update attributes on master, all the links will fail. Substituting the attributes during synchronization did not work because we have been syncing several branches with the same script - SATELLITE-6.7, 6.8, 6.8-beta.
So my plan was to update the attributes _after_ the 6.8 release. That way we do not break anything the only thing that might not be "correct" is that for the time of beta the master branch does not have all the "latest" updates for the attributes because all the latest updates are on SATELLITE-6.8. But I think that is fine. 
I will now go on and update the attributes. I can even do this by finding a correct commit and just cherry-picking from SATELLITE-6.8 to master, I need to take a look if this will work.
> 
> Also I see that in #293 links are being manually updated rather than using ProductVersion variable. This seems suboptimal and regressive and will lead to problems a few weeks down the road.
Suyog probably missed that issue out.

**Comment by melcorr** [comment]
Thanks for the explanation @spetrosi 

Hopefully @suyogsainkar or @lamek can fix the error that was introduced sometime soon before it comes back to bite.

**Comment by spetrosi** [comment]
For the record, I was able to find PRs opened for the SATELLITE-6.8 branch by using the `is:pr is:closed base:SATELLITE-6.8` filter when searching PRs on our repo.
However, the filter also finds PRs opened for `SATELLITE-6.8-beta` branch, because this string includes SATELLITE-6.8 in it, no idea how to restrict the filter.
I have cherry-picked changes to attributes.adoc to master.

**Comment by suyogsainkar** [comment]
@melcorr Thanks for raising this issue. I spotted the beta link the other night and rushed into making that change without using the attribute; my apologies. This has been fixed in #302
