### ISSUE TITLE
Linkchecker very slow, often times out

### ISSUE THREAD

**Issue by apinnick** [theforeman/foreman-documentation#3166]
I have noticed that the linkchecker often fails because of a timeout. It runs very slowly because it builds every guide and then checks the links.

Is there any way we could have the linkchecker check only changed files in the PR instead of all guides?

**Comment by ekohl** [comment]
I doubt it. We'd need to essentially parse the diff and extract URLs from that. That's very complicated.

Another aspect is that today we find broken links because we regularly submit PRs. If we only check for diffs then we need to run it regularly for our various branches and somehow report that. In my experience that's also problematic. We already see people ignore the failed check on the PRs (which IMHO they shouldn't). Ignoring additional reports is much easier.

My suspicion is that if we implement your suggestion, we might as well drop the whole linkchecker.

**Comment by Lennonka** [comment]
I think it's good that it checks all links every time. Thanks to that we have a chance to expired targets. I don't mind personally that it takes a long time and some links time out.

**Comment by apinnick** [comment]
Makes sense. I'll close this issue.
