### ISSUE TITLE
Handle versioning in URLs

### ISSUE THREAD

**Issue by ekohl** [theforeman/foreman-documentation#322]
Currently https://docs.theforeman.org/ doesn't handle versioning at all. It looks like it uses the git branch name as a directory, but that's not very useful if the branch names don't map to anything.

Nowhere in our currently layout on theforeman.org we use `master`. It is either `develop` (after the git branch name) or `nightly`. See https://theforeman.org/manuals/nightly/index.html for example. We also have an Apache redirect from the current nightly version. At the time of writing https://theforeman.org/manuals/2.4/index.html redirects to nightly. This is to support Foreman's [documentation_url](https://github.com/theforeman/foreman/blob/develop/app/controllers/links_controller.rb#L36-L39) which only knows about the versions.

My proposal is that the default branch in this repo is renamed from `master` to something else. Either `nightly` or whatever the nightly version is at that moment would be my preference.

IMHO this policy change is a blocker to actually referencing people to this documentation.

**Comment by melcorr** [comment]
@spetrosi do you see any difficulty with pushing ahead with this? Would you know the areas in the upstream-downstream jobs that we'd need to update?

**Comment by spetrosi** [comment]
I would say that changing master to nightly in the Foreman docs URL works fine. Upstream users would know what this means. The docs do not have any branching right now, I think we have resources only to cover the very latest "nightly" versions. Changing the URLs should be relatively easy, we will need to chang the publishing in the repo and maybe also contact DNS folks.
Let's do this after the issue #192 is resolved. I plan to finish with #192 by the end of January.

**Comment by lzap** [comment]
I don't mind either. For me `develop` would be more consistent with my current scripts and shell aliases but `nightly` is as good.

Having said that, git branches and directories where content is being published are two different things. We can keep the main branch named `master` while publishing the content in `/nightly` directory in `gh-pages`. It's just a single change here: https://github.com/theforeman/foreman-documentation/blob/master/.github/workflows/deploy.yml#L134-L135

The plan was to add additional Foreman branches as new documentation stabilizes, currently we only have `master` (and few Satellite branches - these are solely for downstream purpose although I encouraged our docs team to create separate gitlab repository).

Because symlinks do work on gh-pages (https://github.com/chetabahana/symlink) how about this:

* We keep the `master` branch.
* We keep publishing to `public/master`.
* I create a commit in `gh-pages` with symlink `nightly -> master`.
* I create a commit in `gh-pages` with symlink `develop -> master`.
* I change our web to point to nightly by default.

This way we will not break any existing links and continue using what's expected and our docs team is used to while allowing linking as expected by old docs and Foreman app.

**Comment by ekohl** [comment]
Publishing the same content in multiple places is bad for SEO. There may be ways around that, but by default search engines punish you for it. I'd advise to have a single canonical URL.

**Comment by lzap** [comment]
Hmm, let's keep the branch as `master` but change the publishing directory to `nightly` then. Could you help by creating a redirect in our Apache configuration from `master` to `nightly` to keep our current links which are spread all over our discourse working? Here is the change: https://github.com/theforeman/foreman-documentation/pull/360

**Comment by lzap** [comment]
For some reason, I had an impression that the github pages we deploy into are hosted on our infra. Of course, this can't work.

I will go for either symlink or custom 404 page with javascript that will detect the rename and automatically redirect.

**Comment by ekohl** [comment]
I think by now this is resolved. If anything new pops up, a new issue is better.
