### ISSUE TITLE
Hashtags before commands in code blocks

### ISSUE THREAD

**Issue by maximiliankolb** [theforeman/foreman-documentation#327]
Hi!

I have a question and want to start a discussion/have a proposal to make:

1. What's the reasoning behind using `# ` before any commands in code blocks? Example: [hammer command](https://docs.theforeman.org/master/Provisioning_Guide/index-foreman.html#setting-the-provisioning-context_provisioning)
2. I propose to remove this hashtag and single whitespace. This makes it possible to a) have syntax highlighting (shell commands starting with `#` are treated as a comment and therefore not highlighted) and b) allow for simple "copy and paste". While we probably should not recommend blindly copying and pasting commands from the internet, the first argument really helps to create a better experience with the new documentation.

If there has been some discussion and the community is open to it, I would love to make this happen in multiple PRs, chapter by chapter.

Stay safe everyone,
Maximilian.

**Comment by maximiliankolb** [comment]
If there are reasons for characters before the actual command, this would be another possible solution:

Using css to display a hashtag/dollar sign before each command in a code block:

```
.code_block::before {
  content: "# ";
  margin-right: 0.5rem;
}
```

This allows for smooth copy and pasting (assuming the code block is in a div called `code_block`).

**Comment by ekohl** [comment]
> What's the reasoning behind using `# ` before any commands in code blocks? Example: [hammer command](https://docs.theforeman.org/master/Provisioning_Guide/index-foreman.html#setting-the-provisioning-context_provisioning)

This is a convention that matches your terminal. `#` is for root commands, `$` for normal user commands. The output is then not prefixed. Note that Github flavored markdown recognizes this as well using the console highlighting.

```console
# whoami
root
$ whoami
ekohl
```

`#` and `$` come from your `$PS1` variable which contains `\$`. This automatically uses the correct character, depending on whether you're root or not.

This means that hammer commands technically could use `$` since it can be executed as non-root.

**Comment by maximiliankolb** [comment]
OK, thanks for clarifying @ekohl .

My intention is to use syntax highlighting, which is kinda rough with interactive shell sessions and commands prefixed with `#`.

Long story short: a PR changing this will most likely not be accepted then?

**Comment by ekohl** [comment]
I'm not on the docs team, I'm just helping you understand the convention behind it. Perhaps there's some nice asciidoc magic that can be done to convert it to CSS but I'm looking at the docs folks to answer it really.

**Comment by spetrosi** [comment]
>     1. What's the reasoning behind using `# ` before any commands in code blocks? Example: [hammer command](https://docs.theforeman.org/master/Provisioning_Guide/index-foreman.html#setting-the-provisioning-context_provisioning)
Hi @maximiliankolb, @ekohl described the reasoning correctly, it is to show readers what user should enter this command. See [9.1. Configuring Foreman server for KVM Connections](https://docs.theforeman.org/master/Provisioning_Guide/index-foreman.html#configuring-server-for-kvm-connections_kvm-provisioning) where it is actually useful.

>     2. I propose to remove this hashtag and single whitespace. This makes it possible to a) have syntax highlighting (shell commands starting with `#` are treated as a comment and therefore not highlighted)
It never broke syntax in the published docs because the commands are always written in command blocks. Do you mean the syntax in your text editor? My GVim identifies command blocks and does not highlight anything in them, I think there should be some highlighting hack in your favourite text editor too.
>     and b) allow for simple "copy and paste". While we probably should not recommend blindly copying and pasting commands from the internet, the first argument really helps to create a better experience with the new documentation.
I do not see this as a copy-paste issue, and I like your argument about not blindly copying commands :)

**Comment by maximiliankolb** [comment]
My experience is that is breaks syntax highlighting in the HTML output, which could look as follows:
<img width="402" alt="syntax_highlighting_example" src="https://user-images.githubusercontent.com/12595287/103867808-423e6a00-50c8-11eb-93a3-28f0fbd417c0.png">

[source](https://docs.asciidoctor.org/asciidoc/latest/verbatim/source-blocks/)

**Comment by spetrosi** [comment]
If you enclose the code into a code block then the highlighting works fine in an askiidoc build, like this:
```
----
# ./bootstrap.py \
-s "example" \
-a "any code"
----`
```

**Comment by maximiliankolb** [comment]
OK, then this is more of a bug in Antora (the software we use to produce HTML output from asciidoc source files).

So far, we've always been using `[source,bash]` for shell commands, whereas using syntax highlighting seems to be the exception. I've found one [example](https://docs.theforeman.org/master/Provisioning_Guide/index-foreman.html#updating-the-details-of-multiple-operating-systems_provisioning) with two code blocks, one using `bash`, the second one none.

Thanks. I will close this issue for now.

**Comment by spetrosi** [comment]
We only use the [source,bash] syntax for bash scripts, not for normal CLI commands.
