### ISSUE TITLE
Foreman 3.13 "Katello on EL" dropdown mentions Nightly

### ISSUE THREAD

**Issue by ianballou** [theforeman/foreman-documentation#3496]
![image](https://github.com/user-attachments/assets/b06366a0-f857-4ed3-84de-24666046e834)

It should say "Upgrading Katello to 4.15".

**Comment by ekohl** [comment]
The cause is here:
https://github.com/theforeman/foreman-documentation/blob/8b10b8685a7699c085999b86d295bd78aaf22cd3/web/releases/3.13.json#L18
https://github.com/theforeman/foreman-documentation/blob/8b10b8685a7699c085999b86d295bd78aaf22cd3/web/releases/3.13.json#L48
https://github.com/theforeman/foreman-documentation/blob/8b10b8685a7699c085999b86d295bd78aaf22cd3/web/releases/3.13.json#L90
