### ISSUE TITLE
Integrate 3.1.5 Discovery image kernel options

### ISSUE THREAD

**Issue by lzap** [theforeman/foreman-documentation#44]
Into provisioning guide from https://theforeman.org/plugins/foreman_discovery/15.0/index.html

**Comment by melcorr** [comment]
This will require work before it can be integrated with the docs here. 

If we're going to accept them into the improved doc set, they'll need a more robust definition that covers the "who, what, where, how and why" of each option. 

It is missing context for a new user: where do you set this option? Can one or more of these options be set at the one time? If so, are there any known successful combinations for certain use cases? 

Ideally we would write a procedure where we show users how to set up the Discovery image kernel, so that the user who references this list has also the steps they need to change it.

**Comment by lzap** [comment]
It definitely needs a rework, thus the issue created.

**Comment by melcorr** [comment]
Foreman discovery image currently recognizes the following list of configuration options:

Where are these configuration options set?

**Comment by lzap** [comment]
In the PXELinux (Grub/Grub2) Default Kickstart (Preseed) template. They all use snippets:

* https://github.com/theforeman/community-templates/blob/develop/provisioning_templates/snippet/pxelinux_discovery.erb
* https://github.com/theforeman/community-templates/blob/develop/provisioning_templates/snippet/pxegrub_discovery.erb
* https://github.com/theforeman/community-templates/blob/develop/provisioning_templates/snippet/pxegrub2_discovery.erb

**Comment by maximiliankolb** [comment]
I've added the missing parameters: https://github.com/theforeman/foreman-documentation/pull/2464
