### ISSUE TITLE
We have many unclosed if statements

### ISSUE THREAD

**Issue by lzap** [theforeman/foreman-documentation#467]
Hey @tahliar 

your commit b3937437f937be74f43c1ea8c3465958222dfcd7 introduced some if statements like

    ifdef::context[:parent-context: {context}]

which do not have matching endifs. I honestly do not understand what you meant with these, would you mind fixing those? It looks like build succeeds because preprocessor somehow close them probably at the end of file or whole document. We just see errors in the output:

    asciidoctor: ERROR: common/assembly_performing-additional-configuration-on-capsule-server.adoc: line 28: unmatched preprocessor directive: endif::[]

If you do the following patch to Makefile the build will now fail so you can easily find these:

```diff
diff --git a/guides/common/Makefile b/guides/common/Makefile
index 026b951..e23fa7c 100644
--- a/guides/common/Makefile
+++ b/guides/common/Makefile
@@ -52,7 +52,9 @@ $(IMAGES_TS): $(IMAGES)
        touch $(IMAGES_TS)

 $(DEST_HTML): $(SOURCES)
-       asciidoctor -a build=$(BUILD) -a date_mdy="$(DATE_MDY)" -a date_my="$(DATE_MY)" -a docdatetime="$(DATE_MY)" -a stylesheet=$(BUILD).css -a linkcss=true -b html5 -d book --trace -o $@ $<
+       asciidoctor -a build=$(BUILD) -a date_mdy="$(DATE_MDY)" -a date_my="$(DATE_MY)" -a docdatetime="$(DATE_MY)" -a stylesheet=$(BUILD).css -a linkcss=true -b html5 -d book --trace -o $@ $< 2>&1 | tee $@.log
+       @! grep -q "^asciidoctor: ERROR" $@.log

 $(DEST_PDF): $(SOURCES) $(IMAGES)
-       asciidoctor-pdf -a build=$(BUILD) -d book --trace -o $@ $<
+       asciidoctor-pdf -a build=$(BUILD) -d book --trace -o $@ $< 2>&1 | tee $@.log
+       @! grep -q "^asciidoctor: ERROR" $@.log
```

Thanks

**Comment by tahliar** [comment]
Hi @lzap, those ifdefs are from Red Hat's [assembly template](https://raw.githubusercontent.com/redhat-documentation/modular-docs/master/modular-docs-manual/files/TEMPLATE_ASSEMBLY_a-collection-of-modules.adoc). The files also end with

```
ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]
```

and it's meant to be used primarly when an assembly has its own context, and is included in another assembly with a context, so that the top-level assembly's context is reinstated after the end of the nested assembly (described better [here](https://redhat-documentation.github.io/modular-docs/#nesting-assemblies).)

If it's causing problems in the build, maybe this is something where we need to stray from the guidance Red Hat has provided us so that the markup plays nice with the upstream tools. It's my understanding though that ifdefs can be single-line with no endif, e.g. `ifdef::satellite[This sentence is only relevant to the Satellite build.]` (see [example 3](https://docs.asciidoctor.org/asciidoc/latest/directives/ifdef-ifndef/)).

For the error in common/assembly_performing-additional-configuration-on-capsule-server.adoc, it looks like the problem is an additional endif with no opening ifdef futher down: 

```
ifdef::context[:parent-context: {context}]

[id="performing-additional-configuration-on-capsule-server"]

= Performing Additional Configuration on {SmartProxyServer}

Use this chapter to configure additional settings on your {SmartProxyServer}.

ifdef::katello,satellite[]
// Installing the Katello Agent
include::modules/proc_installing-the-katello-agent.adoc[leveloffset=+1]
endif::[]

// Enabling OpenSCAP
include::modules/proc_enabling-openscap.adoc[leveloffset=+1]

ifdef::katello,satellite[]
// Adding Life Cycle Environments to {SmartProxyServer}s
include::modules/proc_adding-life-cycle-environments.adoc[leveloffset=+1]

endif::[]

// Enabling Power Management on Managed Hosts
include::modules/proc_enabling-power-management-on-managed-hosts.adoc[leveloffset=+1]

// Configuring DNS, DHCP, and TFTP on {SmartProxyServer}
include::modules/proc_configuring-dns-dhcp-and-tftp.adoc[leveloffset=+1]
endif::[]  <<<------

ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]
```

It might have been an accident when the ifevals were swapped over to ifdefs?

**Comment by lzap** [comment]
Oh, I had no idea. From the https://docs.asciidoctor.org/asciidoc/latest/directives/ifdef-ifndef/ document:

If you’re only dealing with a single line of text, you can put the content directly inside the square brackets and drop the endif directive.

Apologies from blaming you and thanks for explanation, this is weird syntax. I am gonna fix this, thank you!

For the record, we can extend the Makefile change also for warnings after we are done with this. We have couple of these:

    asciidoctor: WARNING: /home/lzap/work/foreman-documentation/guides/doc-Content_Management_Guide/master.adoc: stylesheet does not exist or cannot be read: /home/lzap/work/foreman-documentation/guides/doc-Content_Management_Guide/foreman-el.css

**Comment by lzap** [comment]
Fixed in: https://github.com/theforeman/foreman-documentation/pull/469

**Comment by lzap** [comment]
Closing, filed another one about the remaining warnings: https://github.com/theforeman/foreman-documentation/issues/470

Thanks again!
