### ISSUE TITLE
There is no Foreman Upgrade Helper

### ISSUE THREAD

**Issue by melcorr** [theforeman/foreman-documentation#889]
Our docs have some silly nonsense that we need to conditionalise: 

https://docs.theforeman.org/2.5/Upgrading_and_Updating/index-katello.html#upgrading_satellite_server_parent

For interactive upgrade instructions, you can also use the Foreman Upgrade Helper on the Red Hat Customer Portal. This application provides you with an exact guide to match your current version number. You can find instructions that are specific to your upgrade path, as well as steps to prevent known issues. For more information, see Foreman Upgrade Helper on the customer portal.

This needs to be conditionalised for Satellite.

**Comment by melcorr** [comment]
Fixed in #900

**Comment by ekohl** [comment]
As a future reference, you can link a PR. If you do it prior to merging, it will automatically close the issue. On the right side you have "Linked pull requests". That's automatically filled in if you use `Fixes #...` in either the commit or the PR description. You can also do it manually. That's also good because it's happened more than once that I forgot to close the issue when I merged it.
